trying test conditions
Signed-off-by: YelloElefant <alextrotternz@gmail.com>

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -4,6 +4,8 @@ jobs:
   build:
     runs-on: ubuntu-latest
     steps:
+    env:
+      SCIRPT_OUTPUT: ${{steps.compile.outputs.SCIRPT_OUTPUT}}
     - uses: actions/checkout@v2
     - name: Set up JDK 11
       uses: actions/setup-java@v1
@@ -12,4 +14,8 @@ jobs:
     - name: compile code
       run: javac *.java
     - name: run tests
-      run: java resolve google.com hshsd | if grep -q "Unable to resolve"; then echo "Test failed"; exit 1; else echo "Test passed"; fi
+      run: |
+      java resolve google.com hshsd | 
+    - name: Check the output
+      run: echo $SCIRPT_OUTPUT | grep -q "Unable to resolve" && echo "Test Passed" && exit 0 || echo "Test Failed" && exit 1
+        
